### ISSUE TITLE
Doesn't work on Discourse 2.8.14

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/discourse-rad-plugin#6]
As seen on https://discourse.maas.io/t/fresh-installation-of-maas/5128 the Discourse Rad Plugin doesn't work on Discourse v2.8.14

![image](https://github.com/canonical/discourse-rad-plugin/assets/246192/45d80cee-cd2f-4f19-945c-e3d2a1a12ac4)

Note that Discourse 2.8.14 has PLUGIN_API_VERSION 1.1.0

https://github.com/discourse/discourse/blob/df6d323bd187746e254538c81ed29181efc2abe3/app/assets/javascripts/discourse/app/lib/plugin-api.js#L100

**Comment by anthonydillon** [comment]
Can you take a look please?

**Comment by albertkol** [comment]
I followed up on the MAAS channel with information on it.

Initially the plugin was missing. After the installation, we just need to trigger a re-render of the articles, and it will fix the problem. 

Closing.
